"""empty message

Revision ID: e7c93b309149
Revises: e2961329f351
Create Date: 2023-10-09 16:58:49.307971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c93b309149'
down_revision = 'e2961329f351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthyear', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('characters_birtyear_key', type_='unique')
        batch_op.create_unique_constraint(None, ['birthyear'])
        batch_op.drop_column('birtyear')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birtyear', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('characters_birtyear_key', ['birtyear'])
        batch_op.drop_column('birthyear')

    # ### end Alembic commands ###
